### ISSUE TITLE
[Bug]: Teams setting broken

### ISSUE THREAD

**Issue by charizard1596** [Mrbysco/Unhealthy-Dying#15]
### General Info

- [X] I am running a modpack
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

36.2.20

### Mod version

2.2.1 for 1.16.5

### Java version

Java 8 321

### Issue Description

The teams function appears to be completely broken, not working at all by itself or with the regen health setting. Health does not go down per team, but instead affects everyone, and causes buggy behaviour such as setting a players health to one heart upon regenerating health through kills.

**Comment by Mrbysco** [comment]
Fixed by https://github.com/Mrbysco/Unhealthy-Dying/commit/5810c5628386322497841daa96941bbc75e6270f
