### ISSUE TITLE
Transition to another dimension

### ISSUE THREAD

**Issue by kellixon** [Mrbysco/Unhealthy-Dying#2]
MC 1.12.2. Forge 14.23.5.2768. UnhealthyDying 1.0.1+141 mods. All default settings, config folder is clean.
1.During the transition from overworld to nether restores the number of hearts (other dimensions are not checked)
2.After the death of the message at the bottom appear for a short time (is it possible to increase the font or time)

**Comment by Mrbysco** [comment]
There's no way to change the font size/time for the text. It's using the same method the bed uses when you can't sleep.

**Comment by Mrbysco** [comment]
Version 1.1.1 Is now live on curse
