### ISSUE TITLE
[Bug]: There is no config file

### ISSUE THREAD

**Issue by riley-9054** [Mrbysco/Unhealthy-Dying#20]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

43.1.7

### Mod version

2.1.3

### Java version

Java 8 Update 341

### Issue Description

When I downloaded and installed the mod, I then launched the game without going into a world. I then closed the game and checked my "config" folder, and didn't see anything about Unhealthy Dying anywhere in there. After looking for a few minutes, I figured "hm, last time I've had an issue like this with a mod it then generated the config file after I loaded into a world," so I tried that. Text appeared on screen saying my max health was now set to 20, which verified that I did install the mod correctly. Yet when I checked in the "config" folder again there was still nothing about this mod. Not a folder, nor an individual file.

**Comment by Mrbysco** [comment]
The config is located in the world folder
